
name: Update CODEOWNERS

on:
  push:
    branches:
      - feature/workflow-test

jobs:
  update-codeowners:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make changes to the CODEOWNERS file
      - name: Update CODEOWNERS file
        run: |
          echo "# Updated CODEOWNERS file" >> .github/CODEOWNERS
          echo "thimma203" >> .github/CODEOWNERS

      # Step 3: Commit the changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/CODEOWNERS
          git commit -m "Update CODEOWNERS file automatically"

      # Step 4: Push the changes to the repository
      - name: Push changes
        run: |
          git add CODEOWNERS
          git commit -m "updated"
          git push origin feature/workflow-test
        
