---
name: Update Codeowners
on:
  push:
    branches:
      - dev
      - simu
      - prod
      - main

jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Enforce correct codeowners
        run: |
          # Fetch current branch
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Branch detected: $branch"
          touch CODEOWNERS
          # Check which branch we are on
          if [[ "$branch" == "dev" ]]; then
            echo "Updating code owners for DEV branch"
            echo "* @reddy789 @reddy786 - Updated on $(date)" > CODEOWNERS
          elif [[ "$branch" == "simu" || "$branch" == "prod" ]]; then
            echo "Updating code owners for Simu/Prod branch"
            echo "* @reddy789" > CODEOWNERS
          fi
          echo "Current working directory: $(pwd)"
          echo "Verifying CODEOWNERS file..."
          ls -la
          if [ -f CODEOWNERS ]; then
            echo "CODEOWNERS file created successfully"
            cat CODEOWNERS
          else
            echo "CODEOWNERS file not created"
            exit 1
          fi
          echo "Checking git status..."
          git status
      - name: Commit and Push the changes
        run: |
          NAME=${{ github.actor }}
          git config --global user.name "$NAME"
          git add CODEOWNERS
          git commit -m "updated codeowners for branch $branch"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin $branch
